### PR TITLE
Removing registry name, from image name in email subject.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This PR removes name of registry from all email subject lines.

Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Review by dharmit — COMMENTED** [review]
No issues from code point of view. But do we want to remove the registry name from the body of the email as well? So is the sender email going to be the only piece of info that helps end-user understand which pipeline service this email's coming from?

**Comment by mohammedzee1000** [comment]
Ah makes sense, added the registry name back to the body of email only.

**Review by navidshaikh — APPROVED** [review]
LGTM

**Review by navidshaikh — CHANGES_REQUESTED** [review]
I think this will go into the scope of notification PR now and we won't need this PR.

**Comment by dharmit** [comment]
We agreed upon having subject lines like following:
* Success: `[registry.centos.org] SUCCESS: Container build nshaikh/myawesomeproject is complete`
* Failure: `[registry.centos.org] FAILED: Container build nshaikh/myawesomeproject is unsuccessful`

**Pull request closed without merging**
